// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdeqvjvqioijwfzkbmba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkZXF2anZxaW9pandmemtibWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMDk4NDUsImV4cCI6MjA1ODc4NTg0NX0.ga_axhJ0slEFBw40AwVey7KtXTTNHodPegelsfp8hmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);